-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('protocol_pb')
local pb_table = {}

pb_table.HEADER = protobuf.Descriptor();
pb_table.HEADER_STATUS_FIELD = protobuf.FieldDescriptor();
pb_table.HEADER_REQUESTID_FIELD = protobuf.FieldDescriptor();
pb_table.HEADER_USERID_FIELD = protobuf.FieldDescriptor();
pb_table.HEADER_IP_FIELD = protobuf.FieldDescriptor();
pb_table.HEADER_PATH_FIELD = protobuf.FieldDescriptor();

pb_table.HEADER_STATUS_FIELD.name = "status"
pb_table.HEADER_STATUS_FIELD.full_name = ".Header.status"
pb_table.HEADER_STATUS_FIELD.number = 1
pb_table.HEADER_STATUS_FIELD.index = 0
pb_table.HEADER_STATUS_FIELD.label = 1
pb_table.HEADER_STATUS_FIELD.has_default_value = false
pb_table.HEADER_STATUS_FIELD.default_value = 0
pb_table.HEADER_STATUS_FIELD.type = 13
pb_table.HEADER_STATUS_FIELD.cpp_type = 3

pb_table.HEADER_REQUESTID_FIELD.name = "requestId"
pb_table.HEADER_REQUESTID_FIELD.full_name = ".Header.requestId"
pb_table.HEADER_REQUESTID_FIELD.number = 2
pb_table.HEADER_REQUESTID_FIELD.index = 1
pb_table.HEADER_REQUESTID_FIELD.label = 1
pb_table.HEADER_REQUESTID_FIELD.has_default_value = false
pb_table.HEADER_REQUESTID_FIELD.default_value = 0
pb_table.HEADER_REQUESTID_FIELD.type = 13
pb_table.HEADER_REQUESTID_FIELD.cpp_type = 3

pb_table.HEADER_USERID_FIELD.name = "userId"
pb_table.HEADER_USERID_FIELD.full_name = ".Header.userId"
pb_table.HEADER_USERID_FIELD.number = 3
pb_table.HEADER_USERID_FIELD.index = 2
pb_table.HEADER_USERID_FIELD.label = 1
pb_table.HEADER_USERID_FIELD.has_default_value = false
pb_table.HEADER_USERID_FIELD.default_value = 0
pb_table.HEADER_USERID_FIELD.type = 4
pb_table.HEADER_USERID_FIELD.cpp_type = 4

pb_table.HEADER_IP_FIELD.name = "ip"
pb_table.HEADER_IP_FIELD.full_name = ".Header.ip"
pb_table.HEADER_IP_FIELD.number = 4
pb_table.HEADER_IP_FIELD.index = 3
pb_table.HEADER_IP_FIELD.label = 1
pb_table.HEADER_IP_FIELD.has_default_value = false
pb_table.HEADER_IP_FIELD.default_value = ""
pb_table.HEADER_IP_FIELD.type = 9
pb_table.HEADER_IP_FIELD.cpp_type = 9

pb_table.HEADER_PATH_FIELD.name = "path"
pb_table.HEADER_PATH_FIELD.full_name = ".Header.path"
pb_table.HEADER_PATH_FIELD.number = 5
pb_table.HEADER_PATH_FIELD.index = 4
pb_table.HEADER_PATH_FIELD.label = 1
pb_table.HEADER_PATH_FIELD.has_default_value = false
pb_table.HEADER_PATH_FIELD.default_value = ""
pb_table.HEADER_PATH_FIELD.type = 9
pb_table.HEADER_PATH_FIELD.cpp_type = 9

pb_table.HEADER.name = "Header"
pb_table.HEADER.full_name = ".Header"
pb_table.HEADER.nested_types = {}
pb_table.HEADER.enum_types = {}
pb_table.HEADER.fields = {pb_table.HEADER_STATUS_FIELD, pb_table.HEADER_REQUESTID_FIELD, pb_table.HEADER_USERID_FIELD, pb_table.HEADER_IP_FIELD, pb_table.HEADER_PATH_FIELD}
pb_table.HEADER.is_extendable = false
pb_table.HEADER.extensions = {}

Header = protobuf.Message(pb_table.HEADER)

