---
--- Generated by
--- Created by liurenhai.
--- DateTime: 2018/12/27 10:15
---
local csm_pb = require 'csm_pb'

panelChiPai_mj = {}
local this = panelChiPai_mj

local message
local gameObject

local grid
local grid2
local groups={}
local ButtonCanle
local mask
local OPType;
local grid1OriginPos;
local grid2OriginPos;
local bgOriginWidth;
local gridBG;
local cardText;--背景的字体索引

local newOperationData;

local chiIndex = -1

function this.Awake(obj)
    gameObject = obj

    grid = gameObject.transform:Find('Grid');
    grid2 = gameObject.transform:Find('Grid2');
    mask = gameObject.transform:Find('mask');
    gridBG = gameObject.transform:Find('Bg');
    if not grid1OriginPos then
        grid1OriginPos = grid.localPosition;
    end

    if not grid2OriginPos then
        grid2OriginPos = grid2.localPosition;
    end

    if not bgOriginWidth then
        bgOriginWidth = gridBG:GetComponent("UISprite").width;
    end

    message = gameObject:GetComponent('LuaBehaviour')
    message:AddClick(mask.gameObject, this.OnClickMask)

    for i=0,grid.childCount-1 do
        message:AddClick(grid:GetChild(i).gameObject, this.OnClickButtonOk)
        table.insert(groups, grid:GetChild(i))
    end

    for i=0,grid2.childCount-1 do
        message:AddClick(grid2:GetChild(i).gameObject, this.OnClickButtonOk)
        table.insert(groups, grid2:GetChild(i))
    end
end

function this.Start()
end

function this.Update()

end

function this.WhoShow(data)
    cardText = UnityEngine.PlayerPrefs.GetInt('cardText_mj', 1);
    OPType = data.op;
    newOperationData = data.newOperationData;
    print('panelChiPai mahjongs:'..#newOperationData);
    chiIndex = -1
    this.RefreshGrid(grid, newOperationData);
end



function this.OnEnable()

end

function this.OnClickMask(go)
    --print("ButtonGuo:"..tostring(panelInGame.ButtonGuo))
    --panelInGame.OnClickOperationButton(panelInGame.ButtonGuo)
    PanelManager.Instance:HideWindow(gameObject.name)
end

function this.OnClickButtonOk(go)
    chiIndex = GetUserData(go);
    if chiIndex <= 0 then
        return
    end

    AudioManager.Instance:PlayAudio('btn');

    panelInGame.SendMsg(chiIndex,newOperationData);
    --this.OnClickMask(go)
    PanelManager.Instance:HideWindow(gameObject.name);
end




function this.RefreshGrid(grid, ROperationData)
    for i=1,#groups do
        if i <= #ROperationData then
            local item = groups[i];
            item.gameObject:SetActive(true);
            for j=0,item.childCount-1 do
                if j < #ROperationData[i].mahjongs then
                    item:GetChild(j).gameObject:SetActive(true)
                    item:GetChild(j):Find('card'):GetComponent('UISprite').spriteName = panelInGame.GetCardTextName(ROperationData[i].mahjongs[j+1],cardText);
                    item:GetChild(j):GetComponent('UISprite').spriteName = panelInGame.getColorCardName("mj_01",panelInGame.GetCardColor());
                    if ROperationData[i].mahjongs[j+1] == ROperationData[i].mahjong and ROperationData[i].type == csm_pb.CHI then
                        item:GetChild(j):Find("chiPai").gameObject:SetActive(true);
                    else
                        item:GetChild(j):Find("chiPai").gameObject:SetActive(false);

                    end
                else
                    item:GetChild(j).gameObject:SetActive(false)
                end
            end
            SetUserData(item.gameObject, i)
        else
            groups[i].gameObject:SetActive(false)
        end
    end

    local itemCount = #ROperationData;

    this.ResetGridPos(grid,itemCount);
    this.ResetGridPos(grid2,itemCount);

    grid:GetComponent('UIGrid'):Reposition()
    grid2:GetComponent('UIGrid'):Reposition()
end


function this.ResetGridPos(grid,itemCount)

    local count = 1;
    if itemCount > 4 then
        count = 4;
    else
        count = itemCount;
    end

    --1.设置grid的位置
    local posGrid = grid.localPosition;
    posGrid.x = grid1OriginPos.x - ((count-1) * grid:GetComponent("UIGrid").cellWidth);
    print("grid1OriginPos.x="..grid1OriginPos.x);
    grid.localPosition = posGrid;


    --2.设置背景的宽度
    gridBG:GetComponent("UISprite").width = grid:GetComponent("UIGrid").cellWidth * count + 90 ;
    gridBG:GetComponent("UISprite").height = (math.abs(grid:GetComponent("UIGrid").cellHeight)+10)* math.ceil(itemCount/4);



end

