---
--- Generated by 刘仁海
--- Created by 刘仁海.
--- DateTime: 2019/3/5 16:47
---

local csm_pb = require 'csm_pb'
panelSuddenEffect = {};
local this = panelSuddenEffect;
local message;
local gameObject;
local suddenData = nil;
local effectCategoryTrans;
local platesGridTrans;
local platesItemsTrans;

local effectCates = {};
local platesGrids  = {};
local platesPrefabs = {};
local effectCategoryPos = {};


function this.Awake(obj)
    gameObject = obj;
    message  = gameObject:GetComponent("LuaBehaviour");
    this.GetEffectUI();
end


function this.WhoShow(data)
    suddenData = data;
    this.ShowSuddenEffect(suddenData);
end


function this.Start()


end

function this.Update()

end

function this.OnEnable()

end


--显示中途六六顺的特效
function this.ShowSuddenEffect(suddenData)

    --先隐藏所有grid
    for i = 1, 4 do
        platesGrids[i].gameObject:SetActive(false);
    end

    for i = 1, #suddenData do
        local currentIndex = panelInGame.GetUIIndex(panelInGame.GetUIIndexBySeat(suddenData[i].seat),panelInGame.GetPlayerSize())+1;
        print("currentIndex:"..currentIndex);
        local grid = platesGrids[currentIndex];
        grid.gameObject:SetActive(true);
        --.填充牌麻将
        this.SetGridItem(grid,suddenData[i]);
        --.播放特效
        for secdex = 1, #suddenData[i].categories do
            print("secdex:"..secdex);
            print("#suddenData[i].categories:"..(#suddenData[i].categories));
            effManger.ShowCategorieEffect(effectCates[currentIndex].gameObject, suddenData[i].categories[secdex], effectCategoryPos[currentIndex].position);
        end


    end

    --TODO3.播放玩特效后消失
    StartCoroutine(function ()
        WaitForSeconds(2);
        gameObject:SetActive(false);
    end);


end


function this.GetEffectUI()
    effectCategoryTrans     = gameObject.transform:Find("effectCategories");
    platesGridTrans         = gameObject.transform:Find("platesGrids");
    platesItemsTrans        = gameObject.transform:Find("platesItems");
    for i = 1, 4 do
        effectCates[i] = effectCategoryTrans:Find("cate"..i);
        platesGrids[i] = platesGridTrans:Find("grid"..i);
        platesPrefabs[i] = platesItemsTrans:Find("plateItem"..i);
        effectCategoryPos[i] = effectCategoryTrans:Find('cate'..i).position;
    end
end

--设置中途起手胡的麻将信息
function this.SetGridItem(grid,suddenItemData)
    --先隐藏所有item
    for i = 1, grid.childCount do
        local tempChild = grid:GetChild(i-1);
        if tempChild then
            tempChild.gameObject:SetActive(false);
        end
    end

    table.sort(suddenItemData.plates, tableSortAsc);

    if suddenItemData then
        for i = 1, #suddenItemData.plates do
            local setObj = nil;
            local prefabIndex = panelInGame.GetUIIndex(panelInGame.GetUIIndexBySeat(suddenItemData.seat),panelInGame.GetPlayerSize())+1;
            if i <= grid.childCount then
                setObj = grid:GetChild(i-1);
            else

                local tempRotation = platesPrefabs[prefabIndex].localRotation;
                setObj = NGUITools.AddChild(grid.gameObject, platesPrefabs[prefabIndex].gameObject);
                setObj.transform.localRotation = tempRotation;
                --如果是右边的需要修改层级
                if prefabIndex == 2 then
                    setObj:GetComponent("UISprite").depth = 72-i-1;
                    setObj.transform:Find("card"):GetComponent("UISprite").depth = 72-i;
                end
            end

            setObj.gameObject:SetActive(true);
            setObj.transform:Find("card"):GetComponent("UISprite").spriteName = suddenItemData.plates[i];
            setObj.transform:GetComponent("UISprite").spriteName = panelInGame.getColorCardName(CONST.cardPrefabHandDownBg[prefabIndex],panelInGame.GetCardColor());
        end

        grid:GetComponent("UIGrid"):Reposition();
    else
        print("invalid suddenItemData ----------------->"..tostring(suddenItemData));
    end
end


